security:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: login

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        main:
            stateless: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\ApiTokenAuthenticator
            entry_point: App\Security\ApiTokenAuthenticator

    access_control:
        - { path: ^/v1/api/auth/login$, roles: PUBLIC_ACCESS }
        - { path: ^/v1/api/, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
